package javinha.capitulo1;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author archwinlinu
 */
public class JavaChecklist extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public JavaChecklist() {
        setUndecorated(true);
        initComponents();
        setSize(810, 580);
        setLocationRelativeTo(null);
        setTitle("Inicio");
        setResizable(false);
        setDefaultCloseOperation(JavaChecklist.EXIT_ON_CLOSE);
    }

    int xx, xy;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelMain = new javax.swing.JPanel();
        Minimizar = new javax.swing.JLabel();
        Voltar = new javax.swing.JLabel();
        Fechar = new javax.swing.JLabel();
        Superior = new javax.swing.JLabel();
        PanelTexto = new javax.swing.JPanel();
        Icon = new javax.swing.JLabel();
        Texto1 = new javax.swing.JLabel();
        Button1 = new javax.swing.JRadioButton();
        Button2 = new javax.swing.JRadioButton();
        Button3 = new javax.swing.JRadioButton();
        Button4 = new javax.swing.JRadioButton();
        Button5 = new javax.swing.JRadioButton();
        Button6 = new javax.swing.JRadioButton();
        Button7 = new javax.swing.JRadioButton();
        Button8 = new javax.swing.JRadioButton();
        Button9 = new javax.swing.JRadioButton();
        Button10 = new javax.swing.JRadioButton();
        Button11 = new javax.swing.JRadioButton();
        Button12 = new javax.swing.JRadioButton();
        Button13 = new javax.swing.JRadioButton();
        Button14 = new javax.swing.JRadioButton();
        Button15 = new javax.swing.JRadioButton();
        Button16 = new javax.swing.JRadioButton();
        Button17 = new javax.swing.JRadioButton();
        Button18 = new javax.swing.JRadioButton();
        Button19 = new javax.swing.JRadioButton();
        Button20 = new javax.swing.JRadioButton();
        Button = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 580));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(810, 580));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMain.setBackground(new java.awt.Color(255, 255, 255));
        PanelMain.setMinimumSize(new java.awt.Dimension(810, 580));
        PanelMain.setPreferredSize(new java.awt.Dimension(810, 580));
        PanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Minimizar.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        Minimizar.setForeground(new java.awt.Color(171, 171, 171));
        Minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minimizar.setText("-");
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        PanelMain.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 20, 20));

        Voltar.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        Voltar.setForeground(new java.awt.Color(171, 171, 171));
        Voltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Voltar.setText("<");
        Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarMouseClicked(evt);
            }
        });
        PanelMain.add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 20));

        Fechar.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        Fechar.setForeground(new java.awt.Color(171, 171, 171));
        Fechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fechar.setText("X");
        Fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FecharMouseClicked(evt);
            }
        });
        PanelMain.add(Fechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 20, 20));

        Superior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/minimazaExpandeFecha.png"))); // NOI18N
        Superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                SuperiorMouseDragged(evt);
            }
        });
        Superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SuperiorMousePressed(evt);
            }
        });
        PanelMain.add(Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelTexto.setBackground(new java.awt.Color(255, 255, 255));

        Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/java2.png"))); // NOI18N

        Texto1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        Texto1.setForeground(new java.awt.Color(248, 152, 29));
        Texto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto1.setText("Checklist");
        Texto1.setToolTipText("");

        Button1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Button1);
        Button1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Button1.setText("Pergunta 1");
        Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button1MouseClicked(evt);
            }
        });

        Button2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Button2);
        Button2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Button2.setText("Pergunta 2");

        Button3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Button3);
        Button3.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Button3.setText("Pergunta 3");

        Button4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Button4);
        Button4.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Button4.setText("Pergunta 4");

        Button5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Button5);
        Button5.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Button5.setText("Pergunta 5");

        Button6.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Button6);
        Button6.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Button6.setText("Pergunta 6");

        Button7.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Button7);
        Button7.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Button7.setText("Pergunta 7");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        Button8.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Button8);
        Button8.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Button8.setText("Pergunta 8");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });

        Button9.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Button9);
        Button9.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Button9.setText("Pergunta 9");

        Button10.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Button10);
        Button10.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Button10.setText("Pergunta 10");

        Button11.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Button11);
        Button11.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Button11.setText("Pergunta 20");

        Button12.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Button12);
        Button12.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Button12.setText("Pergunta 11");
        Button12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button12MouseClicked(evt);
            }
        });

        Button13.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Button13);
        Button13.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Button13.setText("Pergunta 12");

        Button14.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Button14);
        Button14.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Button14.setText("Pergunta 13");

        Button15.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Button15);
        Button15.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Button15.setText("Pergunta 14");

        Button16.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Button16);
        Button16.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Button16.setText("Pergunta 15");

        Button17.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Button17);
        Button17.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Button17.setText("Pergunta 16");

        Button18.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Button18);
        Button18.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Button18.setText("Pergunta 17");
        Button18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button18ActionPerformed(evt);
            }
        });

        Button19.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Button19);
        Button19.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Button19.setText("Pergunta 18");
        Button19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button19ActionPerformed(evt);
            }
        });

        Button20.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Button20);
        Button20.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Button20.setText("Pergunta 19");

        Button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao2.png"))); // NOI18N
        Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelTextoLayout = new javax.swing.GroupLayout(PanelTexto);
        PanelTexto.setLayout(PanelTextoLayout);
        PanelTextoLayout.setHorizontalGroup(
            PanelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTextoLayout.createSequentialGroup()
                .addGroup(PanelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTextoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Icon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Texto1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTextoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Button, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE))
                    .addGroup(PanelTextoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(PanelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Button9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Button20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelTextoLayout.setVerticalGroup(
            PanelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTextoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Texto1)
                .addGap(49, 49, 49)
                .addGroup(PanelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTextoLayout.createSequentialGroup()
                        .addComponent(Button1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button10))
                    .addGroup(PanelTextoLayout.createSequentialGroup()
                        .addComponent(Button12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(Button)
                .addGap(24, 24, 24))
        );

        PanelMain.add(PanelTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 810, 560));

        getContentPane().add(PanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 580));
        PanelMain.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseClicked
        // TODO add your handling code here:
        JavaCapitulo1 j = new JavaCapitulo1();
        j.show();
        this.hide();
    }//GEN-LAST:event_VoltarMouseClicked

    private void FecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FecharMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_FecharMouseClicked

    private void ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMouseClicked
        // TODO add your handling code here:
        if (Button1.isSelected() == true) {
            JavaPergunta1 j = new JavaPergunta1();
            j.show();
            this.hide();
        }
        if (Button2.isSelected() == true) {
            JavaPergunta2 j = new JavaPergunta2();
            j.show();
            this.hide();
        }
        if (Button3.isSelected() == true) {
            JavaPergunta3 j = new JavaPergunta3();
            j.show();
            this.hide();
        }
        if (Button4.isSelected() == true) {
            JavaPergunta4 j = new JavaPergunta4();
            j.show();
            this.hide();
        }
        if (Button5.isSelected() == true) {
            JavaPergunta5 j = new JavaPergunta5();
            j.show();
            this.hide();
        }
        if (Button6.isSelected() == true) {
            JavaPergunta6 j = new JavaPergunta6();
            j.show();
            this.hide();
        }
        if (Button7.isSelected() == true) {
            JavaPergunta7 j = new JavaPergunta7();
            j.show();
            this.hide();
        }
        if (Button8.isSelected() == true) {
            JavaPergunta8 j = new JavaPergunta8();
            j.show();
            this.hide();
        }
        if (Button9.isSelected() == true) {
            JavaPergunta9 j = new JavaPergunta9();
            j.show();
            this.hide();
        }
        if (Button10.isSelected() == true) {
            JavaPergunta10 j = new JavaPergunta10();
            j.show();
            this.hide();
        }
        if (Button11.isSelected() == true) {
            JavaPergunta11 j = new JavaPergunta11();
            j.show();
            this.hide();
        }
        if (Button12.isSelected() == true) {
            JavaPergunta12 j = new JavaPergunta12();
            j.show();
            this.hide();
        }
        if (Button13.isSelected() == true) {
            JavaPergunta13 j = new JavaPergunta13();
            j.show();
            this.hide();
        }
        if (Button14.isSelected() == true) {
            JavaPergunta14 j = new JavaPergunta14();
            j.show();
            this.hide();
        }
        if (Button15.isSelected() == true) {
            JavaPergunta15 j = new JavaPergunta15();
            j.show();
            this.hide();
        }
        if (Button16.isSelected() == true) {
            JavaPergunta16 j = new JavaPergunta16();
            j.show();
            this.hide();
        }
    }//GEN-LAST:event_ButtonMouseClicked

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        // TODO add your handling code here:
        setState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void SuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuperiorMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_SuperiorMousePressed

    private void SuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuperiorMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_SuperiorMouseDragged

    private void Button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Button1MouseClicked

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Button12MouseClicked

    private void Button18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button18ActionPerformed

    private void Button19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaChecklist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaChecklist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaChecklist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaChecklist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JavaChecklist().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Button;
    private javax.swing.JRadioButton Button1;
    private javax.swing.JRadioButton Button10;
    private javax.swing.JRadioButton Button11;
    private javax.swing.JRadioButton Button12;
    private javax.swing.JRadioButton Button13;
    private javax.swing.JRadioButton Button14;
    private javax.swing.JRadioButton Button15;
    private javax.swing.JRadioButton Button16;
    private javax.swing.JRadioButton Button17;
    private javax.swing.JRadioButton Button18;
    private javax.swing.JRadioButton Button19;
    private javax.swing.JRadioButton Button2;
    private javax.swing.JRadioButton Button20;
    private javax.swing.JRadioButton Button3;
    private javax.swing.JRadioButton Button4;
    private javax.swing.JRadioButton Button5;
    private javax.swing.JRadioButton Button6;
    private javax.swing.JRadioButton Button7;
    private javax.swing.JRadioButton Button8;
    private javax.swing.JRadioButton Button9;
    private javax.swing.JLabel Fechar;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JPanel PanelTexto;
    private javax.swing.JLabel Superior;
    private javax.swing.JLabel Texto1;
    private javax.swing.JLabel Voltar;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
