/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codestation;

import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author archwinlinu
 */
public class InformacoesSoftware extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public InformacoesSoftware() {
        setUndecorated(true);
        initComponents();
        setSize(410, 290);
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(InformacoesSoftware.EXIT_ON_CLOSE);
    }

    int xx, xy;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMain = new javax.swing.JPanel();
        Fechar = new javax.swing.JLabel();
        Superior = new javax.swing.JLabel();
        Texto2 = new javax.swing.JLabel();
        Texto3 = new javax.swing.JLabel();
        Texto4 = new javax.swing.JLabel();
        Texto5 = new javax.swing.JLabel();
        Texto6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(410, 290));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(410, 290));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMain.setBackground(new java.awt.Color(255, 255, 255));
        PanelMain.setMinimumSize(new java.awt.Dimension(410, 290));
        PanelMain.setPreferredSize(new java.awt.Dimension(410, 290));
        PanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fechar.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        Fechar.setForeground(new java.awt.Color(171, 171, 171));
        Fechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fechar.setText("X");
        Fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FecharMouseClicked(evt);
            }
        });
        PanelMain.add(Fechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 20));

        Superior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/minimazaExpandeFecha.png"))); // NOI18N
        Superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                SuperiorMouseDragged(evt);
            }
        });
        Superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SuperiorMousePressed(evt);
            }
        });
        PanelMain.add(Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        Texto2.setBackground(new java.awt.Color(111, 197, 216));
        Texto2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        Texto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto2.setText("3.1.0");
        PanelMain.add(Texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 390, -1));

        Texto3.setBackground(new java.awt.Color(111, 197, 216));
        Texto3.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        Texto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto3.setText("Atualmente");
        PanelMain.add(Texto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 390, -1));

        Texto4.setBackground(new java.awt.Color(111, 197, 216));
        Texto4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        Texto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto4.setText("https://codestation.cf/documentacao");
        Texto4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Texto4MouseClicked(evt);
            }
        });
        PanelMain.add(Texto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 390, -1));

        Texto5.setBackground(new java.awt.Color(111, 197, 216));
        Texto5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        Texto5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto5.setText("O software se encontra na versão");
        PanelMain.add(Texto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 390, -1));

        Texto6.setBackground(new java.awt.Color(111, 197, 216));
        Texto6.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        Texto6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto6.setText("Você pode entrar a sua documentação no link");
        PanelMain.add(Texto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 390, -1));

        getContentPane().add(PanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 290));
        PanelMain.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuperiorMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_SuperiorMousePressed

    private void SuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuperiorMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_SuperiorMouseDragged

    private void FecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FecharMouseClicked
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_FecharMouseClicked

    private void Texto4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Texto4MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            URI u = new URI("https://codestation.cf/documentacao");
            java.awt.Desktop.getDesktop().browse(u);
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Texto4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacoesSoftware.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacoesSoftware.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacoesSoftware.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacoesSoftware.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InformacoesSoftware().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fechar;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JLabel Superior;
    private javax.swing.JLabel Texto2;
    private javax.swing.JLabel Texto3;
    private javax.swing.JLabel Texto4;
    private javax.swing.JLabel Texto5;
    private javax.swing.JLabel Texto6;
    // End of variables declaration//GEN-END:variables
}
