/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codestation;

import java.awt.Color;
import java.net.URI;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javinha.Javinha;

/**
 *
 * @author archwinlinu
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Main() {
        setUndecorated(true);
        initComponents();
        setSize(810, 580);
        setLocationRelativeTo(null);
        setTitle("Inicio");
        setResizable(false);
        setDefaultCloseOperation(Main.EXIT_ON_CLOSE);
        trocaImg();
    }

    int xx, xy;

    public void trocaImg() {
        Random r = new Random();
        int random = r.nextInt(11);
        random += 1;
        System.out.println("/imagens/wallpaper" + random + ".png");

        
        ImageIcon i = new ImageIcon(getClass().getResource("/imagens/wallpaper" + random + ".png"));
        if(random == 6){
            CodeStation.setForeground(Color.BLACK);
        }
        Fundo.setIcon(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMain = new javax.swing.JPanel();
        Git = new javax.swing.JLabel();
        CodeStation = new javax.swing.JLabel();
        JavaScript = new javax.swing.JLabel();
        Java = new javax.swing.JLabel();
        Minimizar = new javax.swing.JLabel();
        Ajuda1 = new javax.swing.JLabel();
        Ajuda = new javax.swing.JLabel();
        Fechar = new javax.swing.JLabel();
        Superior = new javax.swing.JLabel();
        Laranja = new javax.swing.JLabel();
        Amarelo = new javax.swing.JLabel();
        PanelFundo = new javax.swing.JPanel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 580));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(810, 580));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMain.setBackground(new java.awt.Color(255, 255, 255));
        PanelMain.setMinimumSize(new java.awt.Dimension(810, 580));
        PanelMain.setPreferredSize(new java.awt.Dimension(810, 580));
        PanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Git.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Git.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/githubinho.png"))); // NOI18N
        Git.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GitMouseClicked(evt);
            }
        });
        PanelMain.add(Git, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 70, 60));

        CodeStation.setBackground(new java.awt.Color(255, 255, 255));
        CodeStation.setFont(new java.awt.Font("Monospaced", 0, 48)); // NOI18N
        CodeStation.setForeground(new java.awt.Color(255, 255, 255));
        CodeStation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CodeStation.setText("</CodeStation>");
        CodeStation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CodeStationMouseClicked(evt);
            }
        });
        PanelMain.add(CodeStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 810, 280));

        JavaScript.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JavaScript.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/javascriptinhofilho.png"))); // NOI18N
        JavaScript.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JavaScriptMouseClicked(evt);
            }
        });
        PanelMain.add(JavaScript, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 400, 280));

        Java.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Java.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/javinha.png"))); // NOI18N
        Java.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JavaMouseClicked(evt);
            }
        });
        PanelMain.add(Java, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 400, 280));

        Minimizar.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        Minimizar.setForeground(new java.awt.Color(171, 171, 171));
        Minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minimizar.setText("-");
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });
        PanelMain.add(Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 20, 20));

        Ajuda1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        Ajuda1.setForeground(new java.awt.Color(171, 171, 171));
        Ajuda1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ajuda1.setText("</>");
        Ajuda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ajuda1MouseClicked(evt);
            }
        });
        PanelMain.add(Ajuda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, -1, 20));

        Ajuda.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        Ajuda.setForeground(new java.awt.Color(171, 171, 171));
        Ajuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ajuda.setText("?");
        Ajuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AjudaMouseClicked(evt);
            }
        });
        PanelMain.add(Ajuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 20, 20));

        Fechar.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        Fechar.setForeground(new java.awt.Color(171, 171, 171));
        Fechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fechar.setText("X");
        Fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FecharMouseClicked(evt);
            }
        });
        PanelMain.add(Fechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 20, 20));

        Superior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/minimazaExpandeFecha.png"))); // NOI18N
        Superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                SuperiorMouseDragged(evt);
            }
        });
        Superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SuperiorMousePressed(evt);
            }
        });
        PanelMain.add(Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Laranja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/java.png"))); // NOI18N
        Laranja.setToolTipText("");
        PanelMain.add(Laranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        Amarelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/javascript.png"))); // NOI18N
        PanelMain.add(Amarelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 300, 410, -1));

        PanelFundo.setBackground(new java.awt.Color(255, 255, 255));

        Fundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PanelFundoLayout = new javax.swing.GroupLayout(PanelFundo);
        PanelFundo.setLayout(PanelFundoLayout);
        PanelFundoLayout.setHorizontalGroup(
            PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelFundoLayout.setVerticalGroup(
            PanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFundoLayout.createSequentialGroup()
                .addComponent(Fundo, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelMain.add(PanelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 810, 280));

        getContentPane().add(PanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 580));
        PanelMain.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JavaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JavaMouseClicked
        // TODO add your handling code here:
        Javinha j = new Javinha();
        j.show();
        this.hide();
    }//GEN-LAST:event_JavaMouseClicked

    private void FecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FecharMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_FecharMouseClicked

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        // TODO add your handling code here:
        setState(ICONIFIED);
    }//GEN-LAST:event_MinimizarMouseClicked

    private void SuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuperiorMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_SuperiorMouseDragged

    private void SuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SuperiorMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_SuperiorMousePressed

    private void GitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GitMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            URI u = new URI("https://github.com/Dalacorte/code-station");
            java.awt.Desktop.getDesktop().browse(u);
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GitMouseClicked

    private void JavaScriptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JavaScriptMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Esta linguaguem ainda não está disponível\nSentimos muito");
    }//GEN-LAST:event_JavaScriptMouseClicked

    private void AjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AjudaMouseClicked
        // TODO add your handling code here:
        Ajuda a = new Ajuda();
        a.show();
        this.hide();
    }//GEN-LAST:event_AjudaMouseClicked

    private void CodeStationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CodeStationMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            URI u = new URI("https://codestation.cf");
            java.awt.Desktop.getDesktop().browse(u);
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CodeStationMouseClicked

    private void Ajuda1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ajuda1MouseClicked
        // TODO add your handling code here:
        String[] args = new String[10000];
        Navegador.main(args);
    }//GEN-LAST:event_Ajuda1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ajuda;
    private javax.swing.JLabel Ajuda1;
    private javax.swing.JLabel Amarelo;
    private javax.swing.JLabel CodeStation;
    private javax.swing.JLabel Fechar;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Git;
    private javax.swing.JLabel Java;
    private javax.swing.JLabel JavaScript;
    private javax.swing.JLabel Laranja;
    private javax.swing.JLabel Minimizar;
    private javax.swing.JPanel PanelFundo;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JLabel Superior;
    // End of variables declaration//GEN-END:variables
}
